# Maze Solver Configuration

# Maze Generation Settings
maze:
  default_width: 20
  default_height: 20
  default_randomness: 0.1

# Solving Algorithm Settings
algorithms:
  default: 'bfs'
  available:
    - 'bfs'
    - 'dfs'
    - 'astar'
    - 'dijkstra'

# Visualization Settings
visualization:
  figure_size:
    width: 10
    height: 10
  colors:
    wall: 'black'
    path: 'white'
    start: 'green'
    end: 'red'
    solution:
      bfs: 'blue'
      dfs: 'purple'
      astar: 'orange'
      dijkstra: 'cyan'
  animation:
    interval: 50  # milliseconds

# CLI Settings
cli:
  description: "Maze Generation and Solving CLI"
  epilog: "For more information, visit: https://github.com/pmarcowski/maze-solver"
